Add lisongjun
zigpy/zigpy pull request #1039
Opened 2022-08-30 09:54 UTC by lisongjun12

1.add sonoff device OTA function.

2022-08-30 17:27 UTC, puddly commented
Thank you for the pull request.

To ensure your code matches the zigpy project style (and tests pass), please install `pre-commit`:

```
pip install pre-commit
pre-commit install
pre-commit run --all-files  # to fix current issues
```

2022-08-31 03:01 UTC, puddly requested changes
Could you also a unit test including the JSON response sent by your OTA server?  If you modeled it after IKEA's, the unit tests should be almost identical.

2022-08-31 03:14 UTC, lisongjun12 commented on zigpy/__init__.py
> -MINOR_VERSION = 51
OK, I will perform unit tests.
I have not modified the version number. After pulling the code, I see this value. What version number to revert to now?

2022-08-31 03:16 UTC, lisongjun12 commented on zigpy/ota/provider.py
> +                    # SONOFF does not always respond with an appropriate Content-Type
yes,

2022-08-31 03:16 UTC, puddly commented on zigpy/__init__.py
> -MINOR_VERSION = 51
You can see in the diff (https://github.com/zigpy/zigpy/pull/1039/files) the previous value. I think you based your changes off of `master`, not `dev`.

2022-08-31 03:20 UTC, lisongjun12 commented on zigpy/__init__.py
> -MINOR_VERSION = 51
ok, let me check.

2022-08-31 07:02 UTC, closed without merging

2022-08-31 07:04 UTC, lisongjun12 commented
Switch to the dev branch to submit a PR, delete this branch.