Handle special identification for some sensors
zigpy/zigpy pull request #531
Opened 2020-10-29 01:04 UTC by abmantis

This allows sensors like Xiaomi to be initialized without exchanging interview messages.
Requires the following PR in quirks: ?TODO?

2020-10-29 01:22 UTC, puddly commented
Nice! I think this also can be done entirely within quirks by intercepting and instantly responding to basic discovery requests sent by zigpy?

Since quirks already contains the full endpoint and cluster info for a lot of devices, it might be possible to quickly query the model / manufacturer on endpoint 1 (if that uniquely identifies the device) and continue with the full process only if that fails. That should keep Xiaomi-specific code out of core zigpy.

2020-10-29 21:50 UTC, abmantis commented
> Nice! I think this also can be done entirely within quirks by intercepting and instantly responding to basic discovery requests sent by zigpy?
I don't think we can do it all on quirks side, because zigpy replaces the device with the quirk after the init only. So, at the point of init, the device is not a quirk device.

> Since quirks already contains the full endpoint and cluster info for a lot of devices, it might be possible to quickly query the model / manufacturer on endpoint 1 (if that uniquely identifies the device) and continue with the full process only if that fails. That should keep Xiaomi-specific code out of core zigpy.
Are you suggesting sending a network request on cluster 0 to query the model/manuf? I've done that (check the commits before the last one), but @Adminiuga didn't think that is a good idea. Also, we would be adding an extra request for all devices that is not really needed.
And in the case of Xiaomi's they would not reply to that anyway, so we still need to handle the special message before discovery.

2020-11-18 18:03 UTC, abmantis commented
Anything else needed to get this reviewed?

2020-11-18 19:28 UTC, Adminiuga requested changes
That's a lot of effort for little gain. Yeah, xiaomi a pain to pair, but you pair them just once. After that all rejoins are painless even without any cludges. I'd rather see that effort spent on
- multiple entity id support per cluster
- zgp support
- touchlink reset support

I've tried decoupling ZCL general command deserialization to be independent of the device instance and it is doable, **BUT** Xiaomi 🤦 some xiaomi devices send mallformated general commands and requires special treating again.

I don't want to merge it in the current form. will ask to change how it works and split into a number of smaller PRs against a separate branch.
All these PRs must pass existing tests with no or little modifications to the existing tests and all new code must have tests

2020-11-18 19:45 UTC, abmantis commented
> That's a lot of effort for little gain. Yeah, xiaomi a pain to pair, but you pair them just once. After that all rejoins are painless even without any cludges. I'd rather see that effort spent on
> 
>     * multiple entity id support per cluster
> 
>     * zgp support
> 
>     * touchlink reset support

IMO this is a big UX improvement. I had the need to migrate a network with a few Xiaomi sensors, and it sucks. With this, it would take just a second for each sensor.

Also, from a new user POV, ZHA will suck compared to Z2M or Deconz. A lot of new users have Xiaomi sensors. They will install ZHA, try to pair a sensor and it will fail (there's no indication on the UI that you need to press it a lot). Then they'll go to Deconz and it'll just work with a single reset on the sensor. I've heard this story first hand from a friend that tried to use ZHA and ended up in Deconz because he had a lot of Xiaomi sensors and was having a lot of trouble to pair them.

> I've tried decoupling ZCL general command deserialization to be independent of the device instance and it is doable, **BUT** Xiaomi facepalm some xiaomi devices send mallformated general commands and requires special treating again.

I understand that Xiaomi sensors suck spec-wise, but a lot of users have them, so...

> I don't want to merge it in the current form. will ask to change how it works and split into a number of smaller PRs against a separate branch.
> All these PRs must pass existing tests with no or little modifications to the existing tests and all new code must have tests

I don't understand what you want me to change. Just split and add tests?

2020-11-18 19:48 UTC, Adminiuga commented on zigpy/quirks/registry.py
> +                self._model_registry[model].append(custom_device)
I see no point duplicating model lists in `self._registry` dict and in `self._models` 
Can you refactor this into a separate PR where `self._registy` is a dict of manufactures with value of an entry in `self._model` dict?

e.g. something like
```
    def __init__(self, *args, **kwargs):
        dd = collections.defaultdict
        self._model_registry = dd(list)
        self._registry = dd(lambda: self._model_registry)
```

then you don't even need to expose the model registry and no need for 
```
        if manufacturer:
            return self.registry[manufacturer][model]
        return self.model_registry[model]
```

a simple `return self._registry[manufacturer][model] would do it`

2020-11-18 19:51 UTC, puddly commented
What about adding more events that receive objects from registered listeners, like in the OTA code (https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/__init__.py#L72)? This will allow zigpy to notify interested listeners of the device initialization status and allow for device replacement at any point in the process. For example:

 - `device_joined`
 - `node_descriptor`
 - `unsolicited_basic_message` (maybe)
 - `model_manufacturer_info`

Centralizing the `CustomDevice` replacement and keeping it in `application.py` (https://github.com/zigpy/zigpy/pull/521) should help with this. These changes would move all of this special code into zha-device-handlers and keep it out of zigpy. and would also allow for some rudimentary progress to be added to ZHA's web UI.

2020-11-18 19:55 UTC, Adminiuga commented on zigpy/endpoint.py
> +
Nope. Make a `module` method or `CustomDevice` class method to create a device instance from a quirk.
You give it a zigpy device instance and a model and it returns a  Quirk instance. Similar to https://github.com/zigpy/zha-device-handlers/blob/347b5084bf1cbc767e71f916087b6437b3b2d1c8/tests/conftest.py#L77

make this in a second PR

2020-11-18 20:01 UTC, Adminiuga commented
>Also, from a new user POV, ZHA will suck compared to Z2M or Deconz. A lot of new users have Xiaomi sensors. They will install ZHA, try to pair a sensor and it will fail (there's no indication on the UI that you need to press it a lot). 

I've explained it and really we could be more selective and provide more feedback during joining. The problem is not with zigpy, problem that in certain case newly joined devices they complete initialization relatively quickly in zigpy, but the entity in UI is going to show 90s later. That's the problem, not that xiaomi are slowly initializing.

2020-11-18 20:03 UTC, Adminiuga commented
> I personally struggle with joining Xiaomi switches to my network and end up manually editing them into the database so this would be a really useful addition.

The only struggle with xiaomi is to get them to scan the network and do association request. But once you've got the association request in, just keep it awake a few times and you are done

2020-11-18 20:04 UTC, abmantis commented
> > Also, from a new user POV, ZHA will suck compared to Z2M or Deconz. A lot of new users have Xiaomi sensors. They will install ZHA, try to pair a sensor and it will fail (there's no indication on the UI that you need to press it a lot).
> 
> I've explained it and really we could be more selective and provide more feedback during joining. The problem is not with zigpy, problem that in certain case newly joined devices they complete initialization relatively quickly in zigpy, but the entity in UI is going to show 90s later. That's the problem, not that xiaomi are slowly initializing.

I was just referring to xiaomi. I've already changed zha to skip init for xiaomi sensors and it still takes a bit in zigpy (and multiple presses). Not as much as before, ofc.

2020-11-21 21:34 UTC, Adminiuga commented
Closing this in favor of https://github.com/zigpy/zigpy/pull/555 Allows implementing all this in zha-device-handlers without big modifications to zigpy

2020-11-21 21:34 UTC, closed without merging